obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-common.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-mux.o clk-mux-dvf101.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-pll.o clk-pll-dvf.o clk-pll-dvf101.o clk-pll-dvf97.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-div.o clk-div-dvf.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-gate.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-eth.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-usb.o
obj-$(CONFIG_COMMON_CLK_DSPG)	+= clk-mux-regmap.o
