obj-y += cfifo.o coma.o coma-signaling.o

obj-$(CONFIG_DSPG_COMA_SOCKET)     += coma-socket.o
obj-$(CONFIG_DSPG_CSS_TDM)         += coma-tdm.o
obj-$(CONFIG_DSPG_CSS_VOICE)       += coma-voice.o
obj-$(CONFIG_DSPG_CSS_DVF9A)       += coma-dvf9a.o
obj-$(CONFIG_DSPG_CSS_ALSA)        += coma-alsa.o
obj-$(CONFIG_DSPG_CSS_SHAREDMEM)   += coma-sharedmem.o
