# SPDX-License-Identifier: GPL-2.0
#

obj-$(CONFIG_CLKSRC_DSPG_RTC)	+= clksrc-dspg-rtc.o

obj-$(CONFIG_CLKSRC_DSPG_TIMER)		+= clksrc-dspg-timer.o
obj-$(CONFIG_CLKSRC_DSPG)		+= clksrc-dvf-timer.o
obj-$(CONFIG_CLKSRC_DSPG)		+= clksrc-dvf-rtc.o
obj-$(CONFIG_SSE_TIMER)			+= timer-sse.o
