# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.


obj-$(CONFIG_KEYBOARD_BERLIN_IR)	+= berlin-ir.o
obj-$(CONFIG_KEYBOARD_DSPG_TRI)		+= dspg-tri-keypad.o
