# SPDX-License-Identifier: GPL-2.0
#
# Makefile for regulator drivers.
#

obj-$(CONFIG_REGULATOR_HL7593) += hl7593.o
obj-$(CONFIG_REGULATOR_MP886X) += mp886x.o
obj-$(CONFIG_REGULATOR_RT5739) += rt5739-regulator.o
obj-$(CONFIG_REGULATOR_SY8824X) += sy8824x.o
obj-$(CONFIG_REGULATOR_SY8827N) += sy8827n.o
obj-$(CONFIG_REGULATOR_DVF9A) += dvf9a-regulator.o
obj-$(CONFIG_REGULATOR_DVFA10_LDO_DSI) += dvfa10-ldo-dsi-regulator.o
obj-$(CONFIG_REGULATOR_RPI_PANEL_ATTINY) += rpi-panel-attiny-regulator.o