# SPDX-License-Identifier: GPL-2.0-only

obj-$(CONFIG_SYNA_AS370_PLL)	+= as370-pll.o
obj-$(CONFIG_SYNA_DOLPHIN_PLL)	+= dolphin-pll.o
obj-$(CONFIG_SYNA_CLK_BASE)	+= syna-clk.o
syna-clk-y := clk.o gate.o
obj-$(CONFIG_SYNA_AS370_CLK)	+= as370-clks.o
obj-$(CONFIG_SYNA_MYNA_CLK)	+= myna-clks.o
obj-$(CONFIG_SYNA_MYNA2_CLK)	+= myna2-clks.o
obj-$(CONFIG_SYNA_PLATYPUS_CLK)	+= platypus-clks.o
obj-$(CONFIG_SYNA_DOLPHIN_CLK)	+= dolphin-clks.o

