# SPDX-License-Identifier: GPL-2.0-only
obj-$(CONFIG_PINCTRL_BERLIN)		+= berlin.o

obj-$(CONFIG_PINCTRL_MYNA)		+= pinctrl-myna.o
obj-$(CONFIG_PINCTRL_MYNA2)		+= pinctrl-myna2.o
obj-$(CONFIG_PINCTRL_PLATYPUS)		+= pinctrl-platypus.o
obj-$(CONFIG_PINCTRL_DOLPHIN)		+= pinctrl-dolphin.o
obj-$(CONFIG_PINCTRL_SL261X)		+= pinctrl-sl261x.o
