# SPDX-License-Identifier: GPL-2.0
#
# Makefile for multifunction miscellaneous devices
#


obj-$(CONFIG_MFD_DSPG_DVF9A)	+= dvf9a-core.o

ccflags-$(CONFIG_AVIO_MYNA2)	+= -I$(srctree)/drivers/synaptics/soc/berlin/modules/avio/common
