obj-$(CONFIG_DSPG)			+= dsi/

obj-$(CONFIG_DSPG_SEC)			+= sec.o
obj-$(CONFIG_DSPG_CSS)			+= css.o
obj-$(CONFIG_DSPG_CSS)			+= coma/
obj-$(CONFIG_ARCH_DVF101)		+= usb-host-glue.o
obj-$(CONFIG_ARCH_DVF101)		+= usb-phy-mux.o
obj-$(CONFIG_DSPG_CRYPTO)		+= dspg-crypto.o
obj-$(CONFIG_DSPG_DDR_PERF)		+= ddr_perf_cnt.o
obj-$(CONFIG_DSPG_DDR_PMU)		+= dspg_ddr_pmu.o
obj-$(CONFIG_DSPG_TPS65132B2)		+= tps65132b2.o
obj-$(CONFIG_DSPG_PIOG)			+= dspg-guardian.o
obj-$(CONFIG_DSPG_CPUFREQ)		+= dspg-cpufreq.o
obj-$(CONFIG_I2C_SLAVE_DVF99)		+= i2c-slave-dvf99.o
