# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.
obj-$(CONFIG_TOUCHSCREEN_FT7421)	+= ft7421/
obj-$(CONFIG_TOUCHSCREEN_FT5X06)	+= ft5x06/
obj-$(CONFIG_TOUCHSCREEN_DVF9A)		+= dvf9a-ts.o
