# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Wireless network device drivers.
#

subdir-ccflags-y += -Wno-error

obj-$(CONFIG_BCMDHD)	+= bcmdhd/
obj-$(CONFIG_BCMDHD103)	+= bcmdhd103/
obj-$(CONFIG_BCMDHD591)	+= bcmdhd591/
obj-$(CONFIG_BCMDHD361)	+= bcmdhd361/
