# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the Linux Wireless network device drivers.
#


obj-$(CONFIG_BCMDHD)	+= bcmdhd/
obj-$(CONFIG_BCMDHD103)	+= bcmdhd103/
obj-$(CONFIG_BCMDHD591)	+= bcmdhd591/
